#!/bin/bash
[ ! -d "$4" ] && mkdir $4
sshpass -p $3 scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -oKexAlgorithms=diffie-hellman-group1-sha1,diffie-hellman-group-exchange-sha256,diffie-hellman-group14-sha1,diffie-hellman-group14-sha256 $2@$1:/usr/g/service/log/gesys*.log $4
sshpass -p $3 scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -oKexAlgorithms=diffie-hellman-group1-sha1,diffie-hellman-group-exchange-sha256,diffie-hellman-group14-sha1,diffie-hellman-group14-sha256 $2@$1:/usr/g/service/state/ssw.dastools.hist* $4
sshpass -p $3 scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -oKexAlgorithms=diffie-hellman-group1-sha1,diffie-hellman-group-exchange-sha256,diffie-hellman-group14-sha1,diffie-hellman-group14-sha256 $2@$1:/var/log/messages* $4
sshpass -p $3 scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -oKexAlgorithms=diffie-hellman-group1-sha1,diffie-hellman-group-exchange-sha256,diffie-hellman-group14-sha1,diffie-hellman-group14-sha256 $2@$1:/usr/g/service/state/ssw.calreport.hist $4
sshpass -p $3 scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -oKexAlgorithms=diffie-hellman-group1-sha1,diffie-hellman-group-exchange-sha256,diffie-hellman-group14-sha1,diffie-hellman-group14-sha256 $2@$1:/usr/g/service/state/ssw.GenCal.hist $4
sshpass -p $3 scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -oKexAlgorithms=diffie-hellman-group1-sha1,diffie-hellman-group-exchange-sha256,diffie-hellman-group14-sha1,diffie-hellman-group14-sha256 $2@$1:/usr/g/service/state/ssw.tube_align.hist $4
sshpass -p $3 scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -oKexAlgorithms=diffie-hellman-group1-sha1,diffie-hellman-group-exchange-sha256,diffie-hellman-group14-sha1,diffie-hellman-group14-sha256 $2@$1:/usr/g/service/state/air_bubble_detection_result.csv $4
sshpass -p $3 scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -oKexAlgorithms=diffie-hellman-group1-sha1,diffie-hellman-group-exchange-sha256,diffie-hellman-group14-sha1,diffie-hellman-group14-sha256 $2@$1:/usr/g/service/state/TubeSpits.csv $4
sshpass -p $3 scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -oKexAlgorithms=diffie-hellman-group1-sha1,diffie-hellman-group-exchange-sha256,diffie-hellman-group14-sha1,diffie-hellman-group14-sha256 $2@$1:/usr/g/service/state/image_analysis.csv $4