[package]
name = "rust-azure"
version = "0.1.0"
edition = "2021"

[dependencies]
regex = "1"
tokio = { version = "1.37", features = ["full"] }
tokio-postgres = "0.7"
postgres-native-tls = "0.5"
native-tls = { version = "0.2", features = ["vendored"] }
dotenv = "0.15"
deadpool-postgres = "0.13"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["json"] }
tracing-appender = "0.2"
tracing-log = "0.1"  # Optional, if you want to integrate with `log`
chrono = "0.4.41"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
uuid = {version = "1.17.0", features = ["v4"]}
aes = "0.7"
block-modes = "0.8"
block-padding = "0.2"
rand = "0.8"
hex = "0.4"
futures = "0.3"
redis = { version = "0.24", features = ["tokio-comp", "json"] }
reqwest = { version = "0.11", features = ["json", "rustls-tls"] }
base64 = "0.21"
